version: '3'
services:
  app:
    restart: unless-stopped
    image: server-image
    ports:
      - "5000:5000"
    environment:
      - PG_PORT=5432
      - PG_HOST=db
    networks:
      - dz-net
  db:
    image: postgres:16.2
    restart: unless-stopped
    ports:
      - "127.0.0.1:5001:5432"
    volumes:
      - dz_data:/var/lib/postgresql/data
    networks:
      - dz-net
    environment:
      - POSTGRES_PASSWORD=12345

volumes:
  dz_data:

networks:
  dz-net:
